spring:
  datasource:

    #    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:56480/railway
    #    username: postgres
    #    password: jCxAHBhjmrMDZHteDjhzKOjNuhnQOcvO

    url: jdbc:postgresql://localhost:5432/nur_tt
    username: postgres
    password: 1234

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

server:
  forward-headers-strategy: framework