spring:
  application:
    name: nurtt
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

    #    url: jdbc:postgresql://localhost:5432/nur_tt
    #    username: postgres
    #    password: 1234

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never